[mypy]
python_version = 3.12
strict = false
show_error_codes = true
ignore_missing_imports = true
follow_imports = silent
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
warn_return_any = false
warn_unused_configs = false
