"""Multi-Agent框架: 基类/市场洞察/产品规划/商业化/状态机/人机协作/消息协议。"""
from src.agents.base import (
    AgentResult,
    AgentStatus,
    AgentStep,
    AgentTool,
    AgentType,
    BaseAgent,
)
from src.agents.commercial import (
    BusinessPlan,
    CommercialAgent,
    FinancialProjection,
    GoNoGoDecision,
    RiskAssessment,
    create_commercial_agent,
)
from src.agents.human_in_loop import (
    ApprovalConfig,
    ApprovalRequest,
    ApprovalStatus,
    ApprovalType,
    HumanInLoopManager,
    create_human_in_loop_manager,
)
from src.agents.market_insight import (
    CompetitorLandscape,
    MarketInsightAgent,
    MarketSizeEstimate,
    OpportunityScore,
    TrendSignal,
    create_market_insight_agent,
)
from src.agents.message_protocol import (
    AgentMessage,
    MessageBus,
    MessagePriority,
    MessageType,
    create_message_bus,
)
from src.agents.product_planner import (
    CostStructure,
    DifferentiationScore,
    ProductPlannerAgent,
    ProductRecommendation,
    ProductSpec,
    SupplyChainAssessment,
    create_product_planner_agent,
)
from src.agents.selection_master import (
    SelectionMaster,
    SelectionPhase,
    SelectionState,
    SelectionStatus,
    TransitionResult,
    create_selection_master,
)

__all__ = [
    "BaseAgent",
    "AgentTool",
    "AgentStep",
    "AgentResult",
    "AgentStatus",
    "AgentType",
    "MarketInsightAgent",
    "MarketSizeEstimate",
    "CompetitorLandscape",
    "TrendSignal",
    "OpportunityScore",
    "create_market_insight_agent",
    "ProductPlannerAgent",
    "ProductSpec",
    "SupplyChainAssessment",
    "CostStructure",
    "DifferentiationScore",
    "ProductRecommendation",
    "create_product_planner_agent",
    "CommercialAgent",
    "FinancialProjection",
    "RiskAssessment",
    "GoNoGoDecision",
    "BusinessPlan",
    "create_commercial_agent",
    "SelectionMaster",
    "SelectionState",
    "SelectionPhase",
    "SelectionStatus",
    "TransitionResult",
    "create_selection_master",
    "HumanInLoopManager",
    "ApprovalRequest",
    "ApprovalConfig",
    "ApprovalStatus",
    "ApprovalType",
    "create_human_in_loop_manager",
    "AgentMessage",
    "MessageBus",
    "MessageType",
    "MessagePriority",
    "create_message_bus",
]
